#!/bin/sh
#
# AUTOMATICALLY GENERATED!
# DO NOT EDIT THIS FILE!
#
#
java -jar  ../bin/osk-j-mmi.jar  $1
# _______  ____________________  __
#     |                |         |
#     |                |         |  Host name or ip address
#     |                |
#     |                |  OSK MMI Jarfile
#     |
#     |  Java commandline
