#!/bin/sh
#
# AUTOMATICALLY GENERATED!
# DO NOT EDIT THIS FILE!
#
#
java -Duser.timezone=UTC -Dlogback.configurationFile=./logback-sim.xml -jar  ../bin/osk-j-sim.jar  $1  $2
#    ___________________ _____________________________________________ _____ ____________________  __  __
#              |               |                                         |               |         |   |
#              |               |                                         |               |         |   | outtable
#              |               |                                         |               |         |
#              |               |                                         |               |         |  inputfile.xml
#              |               |                                         |               |
#              |               |                                         |               |  OSK SIM Jarfile
#              |               |                                         |
#              |               |                                         |  Java commandline
#              |               |
#              |               |  Set the default logging configuration file.
#              |
#              |  Set the JVM timezone to UTC. This setting is mandatory!
