@echo off
REM AUTOMATICALLY GENERATED!
REM DO NOT EDIT THIS FILE!


java -jar  ../bin/osk-j-mmi.jar  %1
REM _____  ____________________  __
REM   |                |         |
REM   |                |         |  Host name or ip address
REM   |                |
REM   |                |  OSK MMI Jarfile
REM   |
REM   |  Java commandline