@echo off
REM AUTOMATICALLY GENERATED!
REM DO NOT EDIT THIS FILE!


java -Duser.timezone=UTC -Dlogback.configurationFile=./logback-sim.xml -jar  ../bin/osk-j-sim.jar  %1  %2
REM  ___________________ _____________________________________________ _____ ____________________  __  __
REM            |               |                                         |               |         |   |
REM            |               |                                         |               |         |   | outtable
REM            |               |                                         |               |         |
REM            |               |                                         |               |         |  inputfile.xml
REM            |               |                                         |               |
REM            |               |                                         |               |  OSK SIM Jarfile
REM            |               |                                         |
REM            |               |                                         |  Java commandline
REM            |               |
REM            |               |  Set the default logging configuration file.
REM            |
REM            |  Set the JVM timezone to UTC. This setting is mandatory!