package org.osk.console;

// Subwindow class of GUI for cmd typing and for result log display.

import java.awt.Color;
import java.awt.Container;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JInternalFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

// Multiple instances generated by GUI class
public class ChildTextFrame extends JInternalFrame implements KeyListener {
  private String winTitle;
  JTextArea ta;
  Container cp;
  Object mKeyLock = new Object();
  Object mLineLock = new Object();
  String mLastLine;
  int mLastKeyCode = 1;

  public ChildTextFrame(String title)
  {
    super(title, true, true);
    setIconifiable(true);
    setMaximizable(true);
    setBackground(Color.lightGray);

    this.winTitle = title;

    cp = getContentPane();
    ta = new JTextArea (20, 30);
    ta.setTabSize(2);
    ta.setLineWrap(true);
    ta.setWrapStyleWord(true);
    ta.addKeyListener(this);
    cp.add(new JScrollPane(ta));
  }


  public void appendToChildWindow (String theString)
  {
      ta.append(theString);
  }


  public void keyPressed(KeyEvent ke) {
    mLastKeyCode = ke.getKeyCode();
    synchronized(mKeyLock)
    {
      mKeyLock.notifyAll();
    }
    if (ke.getKeyCode() == KeyEvent.VK_ENTER)
    {
      String txt = ta.getText();
      int idx = txt.lastIndexOf('\n', ta.getCaretPosition() - 1) + 1;
      mLastLine = txt.substring(idx != -1 ? idx : 0, ta.getCaretPosition());//txt.length());
      synchronized(mLineLock)
      {
        mLineLock.notifyAll();
      }
    }
  }


  public void keyReleased(KeyEvent ke)
  {
  }


  public void keyTyped(KeyEvent ke)
  {
  }


  public String readLine()
  {
    synchronized(mLineLock)
    {
      try
      {
        mLineLock.wait();
      }
      catch (InterruptedException ex)
      {
      }
    }
    return mLastLine;
  }


  public int read() {
    synchronized(mKeyLock)
    {
      try
      {
        mKeyLock.wait();
      }
      catch (InterruptedException ex)
      {
      }
    }
    return mLastKeyCode;
  }
}
